name: Verify Docker build on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t guide2film3:latest .
    
      - name: Test container runs
        run: |
          docker run --rm guide2film3:latest echo "Container ran successfully"
